#!/usr/bin/env python3
"""Cross-language golden conformance suite (dev-only; not shipped, not in
the zip). Runs every golden PPScript program from the standalone Prospector
Studio repo through the REAL engine interpreter (ScriptRunner in
prospector_engine/engine.py) with a virtual clock, stubbed input, and the shared
IntervalScenario world, then compares the produced trace against the
expected trace generated by the Studio TypeScript VM.

This is the anchor test proving the 3D preview simulates exactly what the
macro engine will do. Run from the repo root:  python3 studio_conformance.py
Must end with:  CONFORMANCE: ALL PASS
"""
import importlib.util
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
GOLDENS = os.path.join(os.path.dirname(ROOT), "ProspectorStudio", "shared", "goldens")
sys.path.insert(0, ROOT)

FAILS = []


def load(path, name):
    spec = importlib.util.spec_from_file_location(name, path)
    m = importlib.util.module_from_spec(spec)
    sys.modules[name] = m
    spec.loader.exec_module(m)
    return m


po = load(os.path.join(ROOT, "prospector_engine", "engine.py"), "pold_conf")

POLL_MS = 25


class Clock:
    def __init__(self):
        self.ms = 0.0

    def adv(self, ms):
        self.ms += max(0.0, ms)


class TimeShim:
    """Replaces the engine module's `time` global with a virtual clock."""

    def __init__(self, clock):
        self._c = clock

    def perf_counter(self):
        return self._c.ms / 1000.0

    def time(self):
        return 1752600000.0

    def sleep(self, s):
        self._c.adv(s * 1000.0)


class Scenario:
    """Mirror of the Studio IntervalScenario (shared/vm/model.ts)."""

    def __init__(self, spec):
        self.spec = spec or {}

    def window(self):
        w = self.spec.get("window") or {"x": 0, "y": 0, "w": 1440, "h": 900}
        return (w["x"], w["y"], w["w"], w["h"])

    def cue(self, cue, t):
        for c, a, b in self.spec.get("cues", []):
            if c == cue and a <= t < b:
                return True
        return False

    def cap(self, t):
        keys = self.spec.get("capacity") or [[0, 0]]
        if t <= keys[0][0]:
            return float(keys[0][1])
        for i in range(1, len(keys)):
            t1, v1 = keys[i - 1]
            t2, v2 = keys[i]
            if t <= t2:
                if t2 == t1:
                    return float(v2)
                return v1 + (v2 - v1) * (t - t1) / float(t2 - t1)
        return float(keys[-1][1])

    def pixel(self, x, y, t):
        for p in self.spec.get("pixels", []):
            if p["x"] == x and p["y"] == y and p["from"] <= t < p["to"]:
                v = int(str(p["color"]).lstrip("#"), 16)
                return ((v >> 16) & 255, (v >> 8) & 255, v & 255)
        return (16, 16, 16)

    def anchor(self, name):
        a = (self.spec.get("anchors") or {}).get(name)
        return (a["x"], a["y"]) if a else None

    def image(self, image_id, threshold, t):
        """Vision rows: images = [{id, from, to, x, y, score}] (ms times,
        score 0..1). Found = any row for this id active at virtual-now
        whose score*100 >= the node's threshold. The probe seam receives
        the search region too, but the scenario model deliberately does
        not filter on it (the TS IntervalScenario mirrors this exactly).
        -> (found, x, y, score) in the _image_probe contract."""
        for row in self.spec.get("images", []):
            if row.get("id") != image_id:
                continue
            if not (row.get("from", 0) <= t < row.get("to", 0)):
                continue
            sc = float(row.get("score", 1.0))
            if sc * 100.0 >= threshold:
                return (True, int(row.get("x", 0)),
                        int(row.get("y", 0)), sc)
        return (False, 0, 0, 0.0)


class DetStub:
    def __init__(self, scen, clock):
        self.s = scen
        self.c = clock
        self.sct = None

    def on_pan(self):
        return self.s.cue("pan", self.c.ms)

    def on_deposit(self):
        return self.s.cue("deposit", self.c.ms)

    def on_shake(self):
        return self.s.cue("shake", self.c.ms)

    def capacity_full(self):
        return self.s.cap(self.c.ms) >= 0.995

    def pan_empty(self):
        return self.s.cap(self.c.ms) <= 0.02

    def cap_fill(self):
        return self.s.cap(self.c.ms)

    def cap_start_rgb(self):
        return self.s.cap(self.c.ms)

    def cap_changed(self, baseline):
        return abs(self.s.cap(self.c.ms) - baseline) > 0.004

    def dig_bar_green(self):
        # v4 dig_green read: scenario models it as a cue named "dig_green"
        # (the TS IntervalScenario mirrors this exactly).
        return self.s.cue("dig_green", self.c.ms)


def norm_val(v):
    if isinstance(v, float) and v == int(v) and abs(v) < 1e15:
        return int(v)
    return v


def run_golden(path):
    golden = json.load(open(path, encoding="utf-8"))
    script = golden["script"]
    scen = Scenario(golden.get("scenario"))
    run = golden.get("run") or {}
    clock = Clock()
    trace = []
    held = []
    state = {"budget_stop": False, "stop_reason": ""}

    def emit(ev, **kw):
        e = {"t": int(round(clock.ms)), "ev": ev}
        e.update(kw)
        trace.append(e)

    # ---- patch the engine module --------------------------------------------
    po.time = TimeShim(clock)
    po.sleep_ms = lambda ms: clock.adv(ms)
    po.find_roblox_rect = lambda: scen.window()

    code_to_tok = {}
    for tok, code in po._SCRIPT_KEYS.items():
        if code is not None:
            code_to_tok[code] = tok
    # v3 keys trace as canonical lowercase names; overlapping codes keep
    # their whitelist token (W not w) per the v3 trace contract.
    for name, code in po.V3_KEYCODES.items():
        code_to_tok.setdefault(code, name)

    def key_down(code):
        tok = code_to_tok.get(code, str(code))
        if tok not in held:
            held.append(tok)
        emit("key_down", key=tok)

    def key_up(code):
        tok = code_to_tok.get(code, str(code))
        if tok in held:
            held.remove(tok)
        emit("key_up", key=tok)

    mouse = {"down": False}

    def mouse_down():
        mouse["down"] = True
        emit("mouse_down")

    def mouse_up():
        mouse["down"] = False
        emit("mouse_up")

    def move_cursor(x, y):
        emit("mouse_move", x=int(x), y=int(y))

    def release_all():
        for tok in list(held):
            held.remove(tok)
            emit("key_up", key=tok)
        if mouse["down"]:
            mouse["down"] = False
            emit("mouse_up")
        for b in list(held_buttons):
            held_buttons.remove(b)
            if b == "left":
                emit("mouse_up")
            else:
                emit("mouse_up", button=b)

    def wait_until(cond, max_ms, confirm=1, min_ms=0):
        # Mirror of the Studio VM waitUntil: virtual 25 ms polls.
        deadline = clock.ms + max_ms
        hits = 0
        while clock.ms < deadline:
            if cond():
                hits += 1
                if hits >= confirm:
                    return True
            else:
                hits = 0
            clock.adv(min(POLL_MS, deadline - clock.ms))
        if cond():
            hits += 1
            return hits >= confirm
        return False

    def safe_stop(msg, hard=False):
        if po.State.running:
            state["stop_reason"] = msg
            po.State.running = False
            emit("stop", reason=msg)

    def post_webhook(event, message, stats=None, shot=False):
        m = message
        if m.startswith("\U0001f4dc "):
            m = m[2:]
        emit("notify", msg=m)

    held_buttons = []

    def button_down(button, click_state=1):
        if button not in held_buttons:
            held_buttons.append(button)
        # left omits the button field so v2 traces stay byte-identical
        if button == "left":
            emit("mouse_down")
        else:
            emit("mouse_down", button=button)

    def button_up(button, click_state=1):
        if button in held_buttons:
            held_buttons.remove(button)
        if button == "left":
            emit("mouse_up")
        else:
            emit("mouse_up", button=button)

    def scroll_lines(amount):
        emit("scroll", amount=int(amount))

    def set_clipboard(text):
        emit("clip", text=str(text))

    po.button_down = button_down
    po.button_up = button_up
    po.scroll_lines = scroll_lines
    po.set_clipboard = set_clipboard

    # type_text traces as ONE aggregated event (the v3 contract: per-key
    # typing timing is not pinned) — mirror the VM's single event + advance.
    def _h_type_text(runner_self, det_, p, kids):
        text = po._sv_text(runner_self._pv_eval((p or {}).get("text", "")))
        text = text[:po._SCRIPT2_STR_MAX]
        cps = runner_self._pi(p, "cps", 18, 2, 50)
        ms = int(-(-len(text) * 1000 // cps))
        emit("type", text=text, ms=ms)
        clock.adv(ms)
        runner_self.pass_activity = True
        return None

    saved_v3_type = po._SCRIPT_HANDLERS_V3.get("type_text")
    po._SCRIPT_HANDLERS_V3["type_text"] = _h_type_text

    po.key_down = key_down
    po.key_up = key_up
    po.mouse_down = mouse_down
    po.mouse_up = mouse_up
    po.move_cursor = move_cursor
    po.release_all = release_all
    po.wait_until = wait_until
    po.safe_stop = safe_stop
    po.post_webhook = post_webhook
    po.log = lambda msg: emit("log", msg=str(msg))

    # v4: emit_event's dirty-set behavior is real semantics (clean-cycle
    # accounting) — mirror it; the event trace row itself comes from the
    # runner's on_event observer, matching the Studio VM exactly.
    def emit_event(etype, reason="", where="", contents="", extra=None):
        if etype in po._DIRTY_EVENTS:
            po.State.cycle_dirty = True
    po.emit_event = emit_event
    po.emit_phase = lambda name: None
    po.RelicScheduler._fire = lambda _self, relic: emit(
        "relic", slot=relic["slot"], clicks=relic["clicks"])

    po.State.running = True
    po.State.alive = True
    po.State.stats = None
    po.State.want_reset = False
    po.State.last_progress = 0.0
    po.State.last_cycle_end = 0.0
    po.State.script_runner = None
    po.State.cycle_dirty = False

    det = DetStub(scen, clock)
    runner = po.ScriptRunner(json.dumps(script), script.get("name"))
    if runner.dead:
        return None, "runner refused the script: %s" % runner.dead
    runner._rand = po._mulberry32(run.get("seed", 1))
    runner._t0 = 0.0
    runner._stuck_at_pass = run.get("stuckAtPass", 0) or 0
    runner._emit_block = lambda b: None
    runner._pixel_rgb = lambda det_, x, y: scen.pixel(x, y, clock.ms)
    runner._image_probe = lambda image_id, region, threshold: scen.image(
        image_id, threshold, clock.ms)
    runner._emit_hud = lambda txt: emit("hud", text=txt)

    def on_set_var(name, value):
        emit("set_var", name=name, value=norm_val(value))
    runner.on_set_var = on_set_var

    # v4 conformance rows: phases, structured events, stat writes.
    runner.on_phase = lambda ph: emit("phase", phase=ph)
    runner.on_event = lambda etype, reason: emit("event", type=etype,
                                                 reason=reason)
    runner.on_stat = lambda stat, op, value: emit("stat", stat=stat, op=op,
                                                  value=norm_val(value))

    max_passes = run.get("maxPasses", 50)

    def on_pass(n):
        emit("pass", n=n)
        if n >= max_passes:
            state["budget_stop"] = True
            runner._suppress_on_stop = True
            po.State.running = False
    runner.on_pass = on_pass

    ticks = 0
    while po.State.running and clock.ms <= 60 * 60 * 1000 and ticks < 500000:
        runner.tick(det)
        ticks += 1

    release_all()
    if state["budget_stop"]:
        reason = "pass budget reached"
    elif state["stop_reason"]:
        reason = "stopped: " + state["stop_reason"]
    else:
        reason = "budget"
    emit("end", reason=reason)

    final_vars = {k: norm_val(v) for k, v in runner.vars.items()}
    return {
        "trace": trace,
        "finalVars": final_vars,
        "passes": runner.passes,
        "virtualMs": int(round(clock.ms)),
        "endReason": reason,
    }, None


def compare(name, got, exp):
    ok = True
    et = exp["trace"]
    gt = got["trace"]
    if len(et) != len(gt):
        print("  [FAIL] %s: %d events, expected %d" % (name, len(gt), len(et)))
        ok = False
    for i in range(min(len(et), len(gt))):
        e, g = et[i], gt[i]
        ge = {k: norm_val(v) for k, v in g.items()}
        ee = {k: norm_val(v) for k, v in e.items()}
        if ge != ee:
            print("  [FAIL] %s event %d:\n    got      %r\n    expected %r"
                  % (name, i, ge, ee))
            ok = False
            break
    if {k: norm_val(v) for k, v in got["finalVars"].items()} != \
            {k: norm_val(v) for k, v in exp.get("finalVars", {}).items()}:
        print("  [FAIL] %s finalVars: got %r expected %r"
              % (name, got["finalVars"], exp.get("finalVars")))
        ok = False
    if got["passes"] != exp.get("passes"):
        print("  [FAIL] %s passes: got %r expected %r"
              % (name, got["passes"], exp.get("passes")))
        ok = False
    if got["virtualMs"] != exp.get("virtualMs"):
        print("  [FAIL] %s virtualMs: got %r expected %r"
              % (name, got["virtualMs"], exp.get("virtualMs")))
        ok = False
    if ok:
        print("  [PASS] %s (%d events, %d ms, %d passes)"
              % (name, len(gt), got["virtualMs"], got["passes"]))
    else:
        FAILS.append(name)


def main():
    if not os.path.isdir(GOLDENS):
        # The goldens live in the private Prospector Studio sibling checkout.
        # A public clone (and public CI) does not have them: that is a SKIP,
        # not a failure -- the equivalent engine behaviour is still covered
        # by the tracked engine_*_tests.py suites and their goldens.
        print("CONFORMANCE: SKIPPED (Studio goldens not present at %s -- "
              "expected on public checkouts)" % GOLDENS)
        sys.exit(0)
    names = sorted(n for n in os.listdir(GOLDENS) if n.endswith(".json"))
    for n in names:
        exp_path = os.path.join(GOLDENS, "expected", n.replace(".json", ".trace.json"))
        if not os.path.isfile(exp_path):
            continue
        got, err = run_golden(os.path.join(GOLDENS, n))
        if err:
            print("  [FAIL] %s: %s" % (n, err))
            FAILS.append(n)
            continue
        exp = json.load(open(exp_path, encoding="utf-8"))
        compare(n, got, exp)
    print()
    print("CONFORMANCE:", "ALL PASS" if not FAILS else "%d FAILURES" % len(FAILS))
    sys.exit(1 if FAILS else 0)


if __name__ == "__main__":
    main()
